export type EnvironmentRow = { key: string; value: string }
export type GroupSummary = { id: string; name: string; parentId: string; path: string; depth: number; declaredEnabled: boolean; effectiveEnabled: boolean; effectiveReason: string; childCount: number; taskCount: number; descendantCount: number; updatedAt: string }
export type TaskSummary = { id: string; name: string; groupId: string; groupPath: string; commandConfigured: boolean; declaredEnabled: boolean; effectiveState: string; effectiveReason: string; lifecycle: string; timezone: string; scheduleSummary: string; policySummary: string; nextRuns: string[]; updatedAt: string }
export type Workspace = { tasks: TaskSummary[]; groups: GroupSummary[]; loadedAt: string }
export type TaskDetail = { id: string; name: string; groupId: string; commandLine: string; workingDir: string; environment: EnvironmentRow[]; stdin: string; runAs: string; enabled: boolean; timezone: string; mode: 'recurring' | 'one_off' | 'manual'; schedule: string; scheduleSyntax: string; at: string; overlapPolicy: string; catchupPolicy: string; missingDatePolicy: string; timeBasis: string; dstGapPolicy: string; dstOverlapPolicy: string; scheduleSummary: string; policySummary: string; readiness: string; updatedAt: string; nextRuns: string[] }
export type TaskDraft = TaskDetail & { isNew: boolean; originalUpdatedAt: string; overwriteStale: boolean }
export type GroupDraft = { id: string; name: string; parentId: string; enabled: boolean; isNew: boolean; originalUpdatedAt: string; overwriteStale: boolean }
export type OperationResult = { action: string; outcome: 'accepted' | 'rejected' | 'stale' | 'unavailable' | 'uncertain'; message: string; field?: string; entityId?: string; workspace?: Workspace; task?: TaskDetail; command?: { program: string; args: string[] } }
export interface TaskBridge { workspace(): Promise<OperationResult>; task(id: string): Promise<OperationResult>; previewTask(draft: TaskDraft): Promise<OperationResult>; saveTask(draft: TaskDraft): Promise<OperationResult>; runTask(id: string): Promise<OperationResult>; setTaskEnabled(id: string, enabled: boolean): Promise<OperationResult>; deleteTask(id: string): Promise<OperationResult>; saveGroup(draft: GroupDraft): Promise<OperationResult>; setGroupEnabled(id: string, enabled: boolean): Promise<OperationResult>; deleteGroup(id: string): Promise<OperationResult>; subscribe?(listener: (event: { kind: string }) => void): () => void }
export const blankTask = (platform = 'unknown'): TaskDraft => ({ id: '', name: '', groupId: '', commandLine: '', workingDir: '', environment: [], stdin: '', runAs: '', enabled: false, timezone: 'Local', mode: 'recurring', schedule: '', scheduleSyntax: '', at: '', overlapPolicy: 'queue_one', catchupPolicy: 'one', missingDatePolicy: 'skip', timeBasis: 'wall_clock', dstGapPolicy: 'next_valid', dstOverlapPolicy: 'first', scheduleSummary: '', policySummary: '', readiness: 'not_runnable', updatedAt: '', nextRuns: [], isNew: true, originalUpdatedAt: '', overwriteStale: false, ...(platform ? {} : {}) })
