import { useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from 'react'
import { Button, Dialog, Field, Notice, StatePanel } from '../components'
import { blankChain, blankSet, blankTrigger, blankWatcher, type AutomationBridge, type ChainDraft, type OperationResult, type SecretResult, type TriggerDraft, type TriggerSetDraft, type WatcherDraft } from './model'
import { useAutomationWorkspace } from './store'

type Editor = { type: 'chain'; draft: ChainDraft } | { type: 'trigger'; draft: TriggerDraft } | { type: 'set'; draft: TriggerSetDraft } | { type: 'watcher'; draft: WatcherDraft }
type SourceType = 'all' | 'chains' | 'triggers' | 'sets' | 'watchers'

export function AutomationPage({ bridge, available = true, refreshToken = 0 }: { bridge: AutomationBridge; available?: boolean; refreshToken?: number }) {
  const { workspace, status, setStatus, load, accept } = useAutomationWorkspace(bridge)
  const [query, setQuery] = useState(''); const [type, setType] = useState<SourceType>('all'); const [attention, setAttention] = useState(false); const [editor, setEditor] = useState<Editor>(); const [secret, setSecret] = useState<SecretResult>(); const [copied, setCopied] = useState(''); const [pending, setPending] = useState(''); const [invoker, setInvoker] = useState<HTMLElement | null>(null); const lastRefresh = useRef(refreshToken)
  useEffect(() => { if (refreshToken !== lastRefresh.current) { lastRefresh.current = refreshToken; void load() } }, [load, refreshToken])
  const matches = (text: string, ready: string) => text.toLowerCase().includes(query.toLowerCase()) && (!attention || !['ready', 'active'].includes(ready))
  const filtered = useMemo(() => ({
    chains: workspace?.chains.filter((v) => matches(`${v.sourceTaskName} ${v.targetTaskName} ${v.onOutcome}`, v.readiness)) ?? [],
    triggers: workspace?.triggers.filter((v) => matches(`${v.name} ${v.targetTaskName}`, v.readiness)) ?? [],
    sets: workspace?.triggerSets.filter((v) => matches(`${v.name} ${v.targetTaskName}`, v.readiness)) ?? [],
    watchers: workspace?.watchers.filter((v) => matches(`${v.name} ${v.path} ${v.pattern} ${v.targetTaskName}`, v.health === 'active' ? v.readiness : v.health)) ?? [],
  // matches is a pure projection of query and attention.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }), [workspace, query, attention])
  const operate = async (key: string, action: () => Promise<OperationResult>) => { if (pending) return; setPending(key); const result = await action(); accept(result); setPending('') }
  const reveal = async (key: string, action: () => Promise<SecretResult>, target: HTMLElement) => { if (pending) return; setPending(key); const result = await action(); setPending(''); setStatus({ action: result.action, outcome: result.outcome, message: result.message, field: result.field }); if (result.outcome === 'accepted' && result.secrets?.length) { setInvoker(target); setSecret(result) }; if (result.outcome === 'accepted') void load() }
  const remove = (label: string, key: string, action: () => Promise<OperationResult>) => { if (window.confirm(`Delete ${label}? This cannot be undone.`)) void operate(key, action) }
  if (!workspace && status?.outcome === 'unavailable') return <PageHeader><StatePanel title="Automation sources are unavailable" detail={status.message} action="Try again" onAction={() => void load()} /></PageHeader>
  if (!workspace) return <PageHeader><StatePanel title="Loading automation sources" detail="Reading every connected source from This computer." busy /></PageHeader>
  const disabled = !available || Boolean(pending)
  const editChain = (v: typeof workspace.chains[number]) => setEditor({ type: 'chain', draft: { id: v.id, sourceTaskId: v.sourceTaskId, targetTaskId: v.targetTaskId, onOutcome: v.onOutcome, originalUpdatedAt: v.updatedAt, isNew: false, overwriteStale: false } })
  const editTrigger = (v: typeof workspace.triggers[number]) => setEditor({ type: 'trigger', draft: { id: v.id, name: v.name, targetTaskId: v.targetTaskId, enabled: v.enabled, originalUpdatedAt: v.updatedAt, isNew: false, overwriteStale: false } })
  const editSet = (v: typeof workspace.triggerSets[number]) => setEditor({ type: 'set', draft: { id: v.id, name: v.name, targetTaskId: v.targetTaskId, count: v.memberCount, enabled: v.enabledCount === v.memberCount, originalUpdatedAt: v.updatedAt, isNew: false, overwriteStale: false } })
  const editWatcher = (v: typeof workspace.watchers[number]) => setEditor({ type: 'watcher', draft: { id: v.id, name: v.name, kind: v.kind, path: v.path, pattern: v.pattern, recursive: v.recursive, debounce: v.debounce, stability: v.stability, targetTaskId: v.targetTaskId, enabled: v.enabled, originalUpdatedAt: v.updatedAt, isNew: false, overwriteStale: false } })
  return <>
    <header className="page-header"><div><p className="eyebrow">This computer</p><h1>Automation Sources</h1><p>Connect task completions, external callers, Trigger Sets, and filesystem changes to local work.</p></div><Button variant="secondary" onClick={() => void load()}>Refresh</Button></header>
    {!available && <Notice title="Read-only context" tone="warning">The last complete workspace remains visible while This computer reconnects. Changes are unavailable.</Notice>}
    {status && status.action !== 'load' && <Notice title={status.outcome === 'accepted' ? 'Complete' : 'Action needed'} tone={status.outcome === 'accepted' ? 'success' : 'error'}>{status.message}</Notice>}
    <section className="panel automation-filters" aria-label="Automation source filters"><Field label="Search"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} /></Field><Field label="Source type"><select value={type} onChange={(event) => setType(event.target.value as SourceType)}><option value="all">All sources</option><option value="chains">Completion chains</option><option value="triggers">External triggers</option><option value="sets">Trigger Sets</option><option value="watchers">Filesystem watchers</option></select></Field><label className="check-field"><input type="checkbox" checked={attention} onChange={(event) => setAttention(event.target.checked)} /> Needs attention only</label></section>
    <div className="automation-sections">
      {(type === 'all' || type === 'chains') && <SourceSection title="Completion chains" count={filtered.chains.length} onCreate={() => setEditor({ type: 'chain', draft: blankChain() })} disabled={disabled}>{filtered.chains.map((v) => <SourceCard key={v.id} title={`${v.sourceTaskName} to ${v.targetTaskName}`} source={`Task completion: ${v.onOutcome}`} target={v.targetTaskName} state={v.readiness} reason={v.reason}><Button variant="secondary" disabled={disabled} onClick={() => editChain(v)}>Edit</Button><Button variant="danger" disabled={disabled} onClick={() => remove('completion chain', `chain:${v.id}`, () => bridge.deleteChain(v.id))}>Delete</Button></SourceCard>)}</SourceSection>}
      {(type === 'all' || type === 'triggers') && <SourceSection title="External triggers" count={filtered.triggers.length} onCreate={() => setEditor({ type: 'trigger', draft: blankTrigger() })} disabled={disabled}>{filtered.triggers.map((v) => <SourceCard key={v.id} title={v.name} source="External key" target={v.targetTaskName} state={v.readiness} reason={v.reason}><Button variant="secondary" disabled={disabled} onClick={() => editTrigger(v)}>Edit</Button><Button variant="secondary" disabled={disabled} onClick={() => void operate(`toggle:${v.id}`, () => bridge.setTriggerEnabled(v.id, !v.enabled))}>{v.enabled ? 'Disable' : 'Enable'}</Button><Button variant="secondary" disabled={disabled} onClick={(event) => void reveal(`reveal:${v.id}`, () => bridge.revealTrigger(v.id), event.currentTarget)}>Reveal</Button><Button variant="secondary" disabled={disabled} onClick={(event) => { if (window.confirm(`Rotate the key for ${v.name}? The old key will stop working immediately.`)) void reveal(`rotate:${v.id}`, () => bridge.rotateTrigger(v.id), event.currentTarget) }}>Rotate</Button><Button disabled={disabled || v.readiness !== 'ready'} onClick={() => void operate(`fire:${v.id}`, () => bridge.fireTrigger(v.id))}>Fire now</Button><Button variant="danger" disabled={disabled} onClick={() => remove(v.name, `delete:${v.id}`, () => bridge.deleteTrigger(v.id))}>Delete</Button></SourceCard>)}</SourceSection>}
      {(type === 'all' || type === 'sets') && <SourceSection title="Trigger Sets" count={filtered.sets.length} onCreate={() => setEditor({ type: 'set', draft: blankSet() })} disabled={disabled}>{filtered.sets.map((v) => <SourceCard key={v.id} title={v.name} source={`${v.enabledCount} of ${v.memberCount} members enabled`} target={v.targetTaskName} state={v.readiness} reason={v.reason}><Button variant="secondary" disabled={disabled} onClick={() => editSet(v)}>Retarget</Button><Button variant="secondary" disabled={disabled} onClick={() => void operate(`toggle-set:${v.id}`, () => bridge.setTriggerSetEnabled(v.id, v.enabledCount !== v.memberCount))}>{v.enabledCount === v.memberCount ? 'Disable all' : 'Enable all'}</Button><Button variant="secondary" disabled={disabled} onClick={(event) => void reveal(`reveal-set:${v.id}`, () => bridge.revealTriggerSet(v.id), event.currentTarget)}>Reveal keys</Button><Button variant="secondary" disabled={disabled} onClick={(event) => { if (window.confirm(`Rotate all ${v.memberCount} keys for ${v.name}? Every old key will stop working immediately.`)) void reveal(`rotate-set:${v.id}`, () => bridge.rotateTriggerSet(v.id), event.currentTarget) }}>Rotate keys</Button><Button variant="danger" disabled={disabled} onClick={() => remove(v.name, `delete-set:${v.id}`, () => bridge.deleteTriggerSet(v.id))}>Delete</Button><details><summary>Ordered members</summary><ol>{v.members.map((member) => <li key={member.id}>{member.position}. {member.name}: {member.readiness}</li>)}</ol></details></SourceCard>)}</SourceSection>}
      {(type === 'all' || type === 'watchers') && <SourceSection title="Filesystem watchers" count={filtered.watchers.length} onCreate={() => setEditor({ type: 'watcher', draft: blankWatcher() })} disabled={disabled}>{filtered.watchers.map((v) => <SourceCard key={v.id} title={v.name} source={`${v.kind}: ${v.path}${v.pattern ? ` (${v.pattern})` : ''}`} target={v.targetTaskName} state={v.health} reason={v.healthReason || v.reason}><Button variant="secondary" disabled={disabled} onClick={() => editWatcher(v)}>Edit</Button><Button variant="secondary" disabled={disabled} onClick={() => void operate(`toggle-watcher:${v.id}`, () => bridge.setWatcherEnabled(v.id, !v.enabled))}>{v.enabled ? 'Disable' : 'Enable'}</Button><Button variant="danger" disabled={disabled} onClick={() => remove(v.name, `delete-watcher:${v.id}`, () => bridge.deleteWatcher(v.id))}>Delete</Button></SourceCard>)}</SourceSection>}
    </div>
    {editor && <SourceEditor editor={editor} tasks={workspace.tasks} bridge={bridge} available={!disabled} onChange={setEditor} onStatus={setStatus} onSecret={(result) => { setSecret(result); void load() }} onSaved={(result) => { accept(result); setEditor(undefined) }} onClose={() => setEditor(undefined)} />}
    <Dialog open={Boolean(secret)} title={secret?.title ? `${secret.title} secrets` : 'Automation source secrets'} invoker={invoker} onClose={() => { setSecret(undefined); setCopied('') }}><Notice title="Store these values safely" tone="warning">Secrets are cleared from this screen when the dialog closes.</Notice><div className="secret-list">{secret?.secrets?.map((item) => <div key={`${item.label}:${item.key}`}><strong>{item.label}</strong><code>{item.key}</code><div className="actions"><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(item.key).then(() => setCopied(`${item.label} key copied.`))}>Copy key</Button><Button variant="secondary" onClick={() => void navigator.clipboard.writeText(item.command).then(() => setCopied(`${item.label} command copied.`))}>Copy command</Button></div></div>)}</div><p role="status">{copied}</p></Dialog>
  </>
}

function PageHeader({ children }: { children: ReactNode }) { return <><header className="page-header"><div><p className="eyebrow">This computer</p><h1>Automation Sources</h1></div></header>{children}</> }
function SourceSection({ title, count, onCreate, disabled, children }: { title: string; count: number; onCreate(): void; disabled: boolean; children: ReactNode }) { return <section className="panel source-section" aria-labelledby={`section-${title.replaceAll(' ', '-').toLowerCase()}`}><div className="section-heading"><h2 id={`section-${title.replaceAll(' ', '-').toLowerCase()}`}>{title}</h2><Button disabled={disabled} onClick={onCreate}>Create</Button></div><p>{count} matching sources</p>{count ? <div className="source-grid">{children}</div> : <StatePanel title={`No matching ${title.toLowerCase()}`} detail="Create a source or change the current filters." />}</section> }
function SourceCard({ title, source, target, state, reason, children }: { title: string; source: string; target: string; state: string; reason: string; children: ReactNode }) { return <article className="source-card"><div><h3>{title}</h3><span className={`source-state state-${state}`}>{state.replaceAll('_', ' ')}</span></div><dl><dt>Source</dt><dd>{source}</dd><dt>Target</dt><dd>{target}</dd><dt>Status</dt><dd>{reason || 'Ready.'}</dd></dl><div className="actions">{children}</div></article> }

function SourceEditor({ editor, tasks, bridge, available, onChange, onStatus, onSecret, onSaved, onClose }: { editor: Editor; tasks: Array<{ id: string; name: string }>; bridge: AutomationBridge; available: boolean; onChange(value: Editor): void; onStatus(value: OperationResult): void; onSecret(value: SecretResult): void; onSaved(value: OperationResult): void; onClose(): void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<OperationResult>(); const formRef = useRef<HTMLFormElement>(null); const invoker = useRef(document.activeElement as HTMLElement | null); const closeRef = useRef(onClose); closeRef.current = onClose; const update = <T extends Editor['draft']>(draft: T) => onChange({ type: editor.type, draft } as Editor)
  useEffect(() => { const focusable = () => Array.from(formRef.current?.querySelectorAll<HTMLElement>('button, input, select, textarea, [href], [tabindex]:not([tabindex="-1"])') ?? []).filter((node) => !node.hasAttribute('disabled')); focusable()[0]?.focus(); const handleKey = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); closeRef.current(); return }; if (event.key !== 'Tab') return; const nodes = focusable(); if (!nodes.length) return; const first = nodes[0]; const last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }; document.addEventListener('keydown', handleKey); return () => { document.removeEventListener('keydown', handleKey); invoker.current?.focus() } }, [])
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (busy || !available) return; setBusy(true)
    if (editor.type === 'chain') { const result = await bridge.saveChain(editor.draft); setBusy(false); if (result.outcome === 'accepted') onSaved(result); else { setError(result); onStatus(result); if (result.outcome === 'stale') update({ ...editor.draft, overwriteStale: true }) }; return }
    if (editor.type === 'watcher') { const result = await bridge.saveWatcher(editor.draft); setBusy(false); if (result.outcome === 'accepted') onSaved(result); else { setError(result); onStatus(result); if (result.outcome === 'stale') update({ ...editor.draft, overwriteStale: true }) }; return }
    if (editor.type === 'set') { const result = editor.draft.isNew ? await bridge.createTriggerSet(editor.draft) : await bridge.retargetTriggerSet(editor.draft.id, editor.draft.targetTaskId, editor.draft.originalUpdatedAt, editor.draft.overwriteStale); setBusy(false); if (result.outcome === 'accepted') { if ('secrets' in result && result.secrets?.length) onSecret(result); else onSaved(result as OperationResult); onClose() } else { setError(result as OperationResult); onStatus(result as OperationResult); if (result.outcome === 'stale') update({ ...editor.draft, overwriteStale: true }) }; return }
    const result = await bridge.saveTrigger(editor.draft); setBusy(false); if (result.outcome === 'accepted') { if (result.secrets?.length) { onSecret(result); onClose() } else { const saved: OperationResult = { action: result.action, outcome: result.outcome, message: result.message, entityId: result.entityId }; onSaved(saved); void bridge.workspace().then((refresh) => refresh.workspace ? onSaved({ ...saved, workspace: refresh.workspace }) : onStatus({ ...saved, message: `${saved.message} Refresh the workspace to see the latest state.` })) } } else { setError(result as OperationResult); onStatus(result as OperationResult); if (result.outcome === 'stale') update({ ...editor.draft, overwriteStale: true }) }
  }
  const label = editor.type === 'set' ? (editor.draft.isNew ? 'Create Trigger Set' : 'Retarget Trigger Set') : `${editor.draft.isNew ? 'Create' : 'Edit'} ${editor.type === 'chain' ? 'completion chain' : editor.type === 'trigger' ? 'external trigger' : 'filesystem watcher'}`
  const target = <Field label="Target task" error={error?.field === 'targetTaskId' ? error.message : undefined}><select value={editor.draft.targetTaskId} onChange={(e) => update({ ...editor.draft, targetTaskId: e.target.value })}><option value="">Select task</option>{tasks.map((task) => <option key={task.id} value={task.id}>{task.name}</option>)}</select></Field>
  return <div className="dialog-backdrop"><form className="dialog editor" aria-label={label} aria-modal="true" role="dialog" ref={formRef} onSubmit={(event) => void submit(event)}><h2>{label}</h2>{error && <Notice title={error.outcome === 'stale' ? 'Newer version found' : 'Review this source'} tone="error">{error.message}</Notice>}<div className="form-grid">
    {editor.type === 'chain' && <><Field label="Source task" error={error?.field === 'sourceTaskId' ? error.message : undefined}><select value={editor.draft.sourceTaskId} onChange={(e) => update({ ...editor.draft, sourceTaskId: e.target.value })}><option value="">Select task</option>{tasks.map((task) => <option key={task.id} value={task.id}>{task.name}</option>)}</select></Field>{target}<Field label="Completion outcome"><select value={editor.draft.onOutcome} onChange={(e) => update({ ...editor.draft, onOutcome: e.target.value })}><option value="success">Success</option><option value="failure">Failure</option><option value="any">Any outcome</option></select></Field> </>}
    {editor.type === 'trigger' && <><Field label="Name" error={error?.field === 'name' ? error.message : undefined}><input value={editor.draft.name} onChange={(e) => update({ ...editor.draft, name: e.target.value })} /></Field>{target}<label className="check-field"><input type="checkbox" checked={editor.draft.enabled} onChange={(e) => update({ ...editor.draft, enabled: e.target.checked })} /> Enabled</label></>}
    {editor.type === 'set' && <><Field label="Name"><input value={editor.draft.name} disabled={!editor.draft.isNew} onChange={(e) => update({ ...editor.draft, name: e.target.value })} /></Field>{target}{editor.draft.isNew && <><Field label="Member count"><input type="number" min="1" max="99" value={editor.draft.count} onChange={(e) => update({ ...editor.draft, count: Number(e.target.value) })} /></Field><label className="check-field"><input type="checkbox" checked={editor.draft.enabled} onChange={(e) => update({ ...editor.draft, enabled: e.target.checked })} /> Members enabled</label></>}</>}
    {editor.type === 'watcher' && <><Field label="Name"><input value={editor.draft.name} onChange={(e) => update({ ...editor.draft, name: e.target.value })} /></Field><Field label="Kind"><select value={editor.draft.kind} onChange={(e) => update({ ...editor.draft, kind: e.target.value as 'file' | 'directory' })}><option value="file">File</option><option value="directory">Directory</option></select></Field><Field label="Path"><input value={editor.draft.path} onChange={(e) => update({ ...editor.draft, path: e.target.value })} /></Field><Field label="Pattern" help="Optional glob for directory watchers."><input value={editor.draft.pattern} onChange={(e) => update({ ...editor.draft, pattern: e.target.value })} /></Field><Field label="Debounce"><input value={editor.draft.debounce} onChange={(e) => update({ ...editor.draft, debounce: e.target.value })} /></Field><Field label="Stability"><input value={editor.draft.stability} onChange={(e) => update({ ...editor.draft, stability: e.target.value })} /></Field>{target}<label className="check-field"><input type="checkbox" checked={editor.draft.recursive} onChange={(e) => update({ ...editor.draft, recursive: e.target.checked })} /> Include subdirectories</label><label className="check-field"><input type="checkbox" checked={editor.draft.enabled} onChange={(e) => update({ ...editor.draft, enabled: e.target.checked })} /> Enabled</label></>}
  </div><div className="actions"><Button type="submit" disabled={!available || busy}>{editor.draft.overwriteStale ? 'Overwrite newer version' : busy ? 'Saving' : 'Save'}</Button><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button></div></form></div>
}
