import { useState } from 'react'
import { Button, Field, FormGrid, Notice } from '../components'

export interface PairingDraft { profile_label: string; repair_profile_id?: string; address: string; daemon_id: string; pairing_id: string; phrase: string; certificate_pem: string; display_name: string; capability: string }
export interface PairingResult { action: string; outcome: string; message: string; credential_id?: string; profile_id?: string }
type NativeWindow = Window & { go?: { main?: { App?: { PairRemote?(draft: PairingDraft): Promise<PairingResult> } } } }

export function PairingForm({ nativeWindow = window, onPaired, repairProfileId = '' }: { nativeWindow?: NativeWindow; onPaired?(): void; repairProfileId?: string }) {
  const [draft, setDraft] = useState<PairingDraft>({ profile_label: '', address: '', daemon_id: '', pairing_id: '', phrase: '', certificate_pem: '', display_name: '', capability: 'observe' })
  const [pending, setPending] = useState(false)
  const [message, setMessage] = useState('')
  const update = (key: keyof PairingDraft, value: string) => setDraft(current => ({ ...current, [key]: value }))
  const pair = async () => { setPending(true); const result = await nativeWindow.go?.main?.App?.PairRemote?.({ ...draft, repair_profile_id: repairProfileId || undefined }) ?? { action: 'pair_remote', outcome: 'unavailable', message: 'Remote pairing is available in the installed desktop application.' }; setMessage(result.message); if (result.outcome === 'accepted') onPaired?.(); setDraft(current => ({ ...current, phrase: '' })); setPending(false) }
  return <form className="pairing-form" onSubmit={(event) => { event.preventDefault(); void pair() }}>{message && <Notice title="Pairing result" tone="info">{message}</Notice>}<p>{repairProfileId ? 'Enter fresh pairing material for the same daemon identity.' : 'Paste the values shown by the administrator exactly.'} The phrase is cleared after the attempt and the durable credential is stored by the operating system.</p><FormGrid><Field label="Profile label"><input value={draft.profile_label} onChange={event => update('profile_label', event.target.value)} /></Field><Field label="HTTPS address"><input value={draft.address} onChange={event => update('address', event.target.value)} placeholder="https://192.0.2.10:8443" /></Field><Field label="Daemon ID"><input value={draft.daemon_id} onChange={event => update('daemon_id', event.target.value)} /></Field><Field label="Pairing ID"><input value={draft.pairing_id} onChange={event => update('pairing_id', event.target.value)} /></Field><Field label="Client display name"><input value={draft.display_name} onChange={event => update('display_name', event.target.value)} /></Field><Field label="Requested capability"><select value={draft.capability} onChange={event => update('capability', event.target.value)}><option value="observe">Observe</option><option value="operate">Operate</option><option value="manage">Manage</option><option value="enroll">Enroll</option></select></Field><Field label="One-time phrase"><input type="password" autoComplete="off" value={draft.phrase} onChange={event => update('phrase', event.target.value)} /></Field><Field label="Trusted certificate (PEM)"><textarea value={draft.certificate_pem} onChange={event => update('certificate_pem', event.target.value)} /></Field></FormGrid><Button pending={pending} type="submit">Pair remote daemon</Button></form>
}
