import { useMemo, useState } from 'react'
import { Button, Notice, StatePanel } from '../components'
import type { ActivityWorkspace, AlertRecord, LogRecord, OperationsBridge, RunRecord } from './model'
import { useActivity } from './store'

type ActivityItem = { id: string; type: 'run' | 'log' | 'alert'; time: string; severity: string; state: string; source: string; summary: string; search: string; raw: RunRecord | LogRecord | AlertRecord }
const label = (value: string) => value.replaceAll('_', ' ').replace(/^./, (char) => char.toUpperCase())
const localTime = (value: string) => new Date(value).toLocaleString()

export function activityItems(workspace?: ActivityWorkspace): ActivityItem[] {
  if (!workspace) return []
  return [
    ...workspace.runs.map((run): ActivityItem => ({ id: `run:${run.id}`, type: 'run', time: run.endedAt ?? run.startedAt ?? run.scheduledFor, severity: run.state === 'failure' ? 'error' : 'info', state: run.state, source: run.taskId || 'Unknown task', summary: `${label(run.state)} run`, search: JSON.stringify(run).toLowerCase(), raw: run })),
    ...workspace.logs.map((log): ActivityItem => ({ id: `log:${log.id}`, type: 'log', time: log.time, severity: log.severity, state: log.severity, source: log.source, summary: log.message, search: JSON.stringify(log).toLowerCase(), raw: log })),
    ...workspace.alerts.map((alert): ActivityItem => ({ id: `alert:${alert.id}`, type: 'alert', time: alert.time, severity: alert.severity, state: alert.acknowledged ? 'acknowledged' : 'unacknowledged', source: label(alert.kind), summary: alert.message, search: JSON.stringify(alert).toLowerCase(), raw: alert })),
  ].sort((a, b) => b.time.localeCompare(a.time))
}

function Detail({ item, missing, canMutate, pending, acknowledge }: { item?: ActivityItem; missing: boolean; canMutate: boolean; pending: boolean; acknowledge(id: string): void }) {
  if (missing) return <aside className="panel operation-detail"><h2>Activity no longer in view</h2><p>The selected record was not present in the latest complete snapshot. Your filters were preserved.</p></aside>
  if (!item) return <aside className="panel operation-detail"><h2>Activity details</h2><p>Select a run, log, or alert to inspect all available evidence.</p></aside>
  if (item.type === 'run') { const run = item.raw as RunRecord; return <aside className="panel operation-detail"><h2>Run details</h2><dl><dt>State</dt><dd>{label(run.state)}</dd><dt>Task ID</dt><dd><code>{run.taskId || 'Unavailable'}</code></dd><dt>Scheduled</dt><dd>{localTime(run.scheduledFor)}</dd><dt>Started</dt><dd>{run.startedAt ? localTime(run.startedAt) : 'Unavailable'}</dd><dt>Ended</dt><dd>{run.endedAt ? localTime(run.endedAt) : 'Unavailable'}</dd><dt>Trigger</dt><dd>{run.trigger || 'Unavailable'}</dd><dt>Exit status</dt><dd>{run.exitCode ?? 'No process exit status'}</dd><dt>Output truncated</dt><dd>{run.outputTruncated ? 'Yes' : 'No'}</dd><dt>Source task</dt><dd><code>{run.sourceTaskId || 'Not applicable'}</code></dd><dt>Source run</dt><dd><code>{run.sourceRunId || 'Not applicable'}</code></dd><dt>Source trigger</dt><dd><code>{run.sourceTriggerId || 'Not applicable'}</code></dd><dt>Source watcher</dt><dd><code>{run.sourceWatcherId || 'Not applicable'}</code></dd></dl><h3>Combined stdout/stderr</h3><pre>{run.output || '(empty)'}</pre></aside> }
  if (item.type === 'log') { const log = item.raw as LogRecord; return <aside className="panel operation-detail"><h2>Daemon log details</h2><dl><dt>Severity</dt><dd>{label(log.severity)}</dd><dt>Time</dt><dd>{localTime(log.time)}</dd><dt>Source</dt><dd>{log.source}</dd><dt>Task ID</dt><dd><code>{log.taskId || 'Unavailable'}</code></dd><dt>Run ID</dt><dd><code>{log.runId || 'Unavailable'}</code></dd></dl><p>{log.message}</p>{log.detail && <pre>{log.detail}</pre>}</aside> }
  const alert = item.raw as AlertRecord
  return <aside className="panel operation-detail"><h2>Alert details</h2><dl><dt>Status</dt><dd>{alert.acknowledged ? 'Acknowledged' : 'Unacknowledged'}</dd><dt>Severity</dt><dd>{label(alert.severity)}</dd><dt>Kind</dt><dd>{label(alert.kind)}</dd><dt>Time</dt><dd>{localTime(alert.time)}</dd><dt>Task ID</dt><dd><code>{alert.taskId || 'Unavailable'}</code></dd><dt>Run ID</dt><dd><code>{alert.runId || 'Unavailable'}</code></dd></dl><p>{alert.message}</p>{!alert.acknowledged && <Button disabled={!canMutate || pending} onClick={() => acknowledge(alert.id)}>Acknowledge alert</Button>}</aside>
}

export function ActivityPage({ bridge, available, refreshToken, targetName = 'This computer', canMutate = available }: { bridge: OperationsBridge; available: boolean; refreshToken: number; targetName?: string; canMutate?: boolean }) {
  const { workspace, status, pending, load, acknowledge } = useActivity(bridge, available, refreshToken)
  const reconciling = status?.outcome === 'uncertain'
  const [query, setQuery] = useState(''); const [type, setType] = useState('all'); const [severity, setSeverity] = useState('all'); const [outcome, setOutcome] = useState('all'); const [selectedID, setSelectedID] = useState(''); const [clearedAt, setClearedAt] = useState('')
  const rows = useMemo(() => activityItems(workspace).filter((item) => (!clearedAt || item.time > clearedAt) && (type === 'all' || item.type === type) && (severity === 'all' || item.severity === severity) && (outcome === 'all' || item.state === outcome) && (!query.trim() || item.search.includes(query.trim().toLowerCase()))), [clearedAt, outcome, query, severity, type, workspace])
  const selected = rows.find((item) => item.id === selectedID); const missing = Boolean(selectedID && workspace && !selected)
  const clear = () => { const alertIDs = rows.filter((item) => item.type === 'alert' && !(item.raw as AlertRecord).acknowledged).map((item) => (item.raw as AlertRecord).id); setClearedAt(new Date().toISOString()); if (alertIDs.length) void acknowledge(alertIDs) }
  return <>
    <header className="page-header"><div><p className="eyebrow">{targetName}</p><h1>Activity</h1><p>Investigate recent runs, daemon logs, and alerts as distinct records.</p></div><Button variant="secondary" onClick={() => void load()} disabled={!available}>Refresh</Button></header>
    {!available && <Notice title="Read-only activity" tone="warning">The last complete activity snapshot remains visible while the scheduler reconnects.</Notice>}
    {status?.outcome !== 'accepted' && status && <Notice title="Activity could not refresh" tone="error">{status.message}</Notice>}
    {workspace && <p className="log-path">This is a limited recent view. Full daemon log: <code>{workspace.logPath || 'unavailable until daemon responds'}</code></p>}
    <section className="panel operation-filters" aria-label="Activity filters"><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} /></label><label>Record type<select value={type} onChange={(event) => setType(event.target.value)}><option value="all">All records</option><option value="run">Runs</option><option value="log">Daemon logs</option><option value="alert">Alerts</option></select></label><label>Severity<select value={severity} onChange={(event) => setSeverity(event.target.value)}><option value="all">All severities</option><option value="info">Info</option><option value="warning">Warning</option><option value="error">Error</option></select></label><label>Outcome or state<select value={outcome} onChange={(event) => setOutcome(event.target.value)}><option value="all">All states</option>{['running', 'success', 'failure', 'skipped', 'caught_up', 'queued', 'unavailable', 'unacknowledged', 'acknowledged'].map((value) => <option value={value} key={value}>{label(value)}</option>)}</select></label><Button variant="secondary" onClick={clear} disabled={!canMutate || reconciling || pending || rows.length === 0}>Clear View</Button><p role="status">{rows.length} matching records</p></section>
    <p>Clear View hides currently matching activity and acknowledges visible alerts. Persisted records are not deleted.</p>
    {!workspace ? <StatePanel title="Loading activity" detail="Requesting one complete recent-activity snapshot." busy={available} /> : rows.length === 0 ? <StatePanel title="No matching activity" detail="Change the filters or wait for new activity. Cleared records remain persisted." /> : <div className="operation-layout"><section className="panel operation-list"><div className="table-scroll" tabIndex={0}><table><caption>Recent runs, daemon logs, and alerts</caption><thead><tr><th scope="col">When</th><th scope="col">Type</th><th scope="col">State</th><th scope="col">Source</th><th scope="col">Summary</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id} aria-selected={item.id === selectedID}><td><button className="row-select" onClick={() => setSelectedID(item.id)}>{localTime(item.time)}</button></td><td>{label(item.type)}</td><td><span className={`operation-state state-${item.state}`}>{label(item.state)}</span></td><td>{item.source}</td><td>{item.summary}</td></tr>)}</tbody></table></div></section><Detail item={selected} missing={missing} canMutate={canMutate && !reconciling} pending={pending} acknowledge={(id) => void acknowledge([id])} /></div>}
  </>
}
