// Package popups observes new daemon activity and presents opt-in desktop-local notifications.
package popups

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"
	"unicode"

	"github.com/shruggietech/go-schedule/desktop/connection"
	"github.com/shruggietech/go-schedule/desktop/settings"
	"github.com/shruggietech/go-schedule/internal/api/client"
	"github.com/shruggietech/go-schedule/internal/api/server"
	"github.com/shruggietech/go-schedule/internal/domain"
)

const maxSources = 64
const maxSeen = 512

// Source is one registration with an immutable expected daemon identity.
type Source struct {
	ProfileID string
	DaemonID  string
	Label     string
	Client    EventClient
	Backend   HealthBackend
}

// EventClient is restricted to read-only observation and exact record reads.
type EventClient interface {
	StreamRemoteEvents(context.Context, func(client.RemoteEvent)) error
	GetRun(context.Context, string) (domain.Run, error)
	GetTask(context.Context, string) (server.TaskResponse, error)
	ListAlertsLimited(context.Context, bool, int) ([]domain.Alert, error)
}

type HealthBackend interface {
	Health(context.Context) (connection.Health, error)
}

// Intent safely identifies an activity record without exposing its contents.
type Intent struct {
	ProfileID string `json:"profileId"`
	DaemonID  string `json:"daemonId"`
	Label     string `json:"label"`
	Kind      string `json:"kind"`
	RecordID  string `json:"recordId"`
}

// Notice is the small platform-neutral native notification payload.
type Notice struct {
	ID     string
	Title  string
	Body   string
	Intent Intent
}

// Presenter is injectable so filtering and lifecycle can be tested without an OS shell.
type Presenter interface {
	Available() bool
	Authorized() bool
	Present(Notice) error
}

type PreferenceReader interface {
	PopupPreferences() (settings.PopupPreferences, error)
}
type SourceLoader func() []Source

// Service owns independent, read-only streams while the desktop process is open.
type Service struct {
	mu        sync.Mutex
	refreshMu sync.Mutex
	root      context.Context
	cancel    context.CancelFunc
	load      SourceLoader
	prefs     PreferenceReader
	presenter Presenter
	seen      map[string]bool
	order     []string
	intents   map[string]Intent
	seq       uint64
}

func New(load SourceLoader, prefs PreferenceReader, presenter Presenter) *Service {
	return &Service{load: load, prefs: prefs, presenter: presenter, seen: make(map[string]bool), intents: make(map[string]Intent)}
}

// Start or Refresh applies the latest opt-in choice without disturbing selected connection state.
func (s *Service) Start(parent context.Context) {
	s.mu.Lock()
	s.root = parent
	s.mu.Unlock()
	s.Refresh()
}

func (s *Service) Refresh() {
	s.refreshMu.Lock()
	defer s.refreshMu.Unlock()
	s.mu.Lock()
	if s.cancel != nil {
		s.cancel()
		s.cancel = nil
	}
	parent := s.root
	s.mu.Unlock()
	if parent == nil || s.presenter == nil || !s.presenter.Available() || !s.presenter.Authorized() {
		return
	}
	prefs, err := s.prefs.PopupPreferences()
	if err != nil || !prefs.Enabled {
		return
	}
	sources := s.load()
	if len(sources) > maxSources {
		sources = sources[:maxSources]
	}
	ctx, cancel := context.WithCancel(parent)
	s.mu.Lock()
	s.cancel = cancel
	s.mu.Unlock()
	for _, source := range sources {
		if source.Client == nil || source.Backend == nil || (source.DaemonID != "" && !included(prefs.DaemonIDs, source.DaemonID)) {
			continue
		}
		go s.observe(ctx, source)
	}
}

func (s *Service) Stop() {
	s.refreshMu.Lock()
	defer s.refreshMu.Unlock()
	s.mu.Lock()
	if s.cancel != nil {
		s.cancel()
		s.cancel = nil
	}
	s.root = nil
	s.mu.Unlock()
}

// Intent returns only a notification generated by this process, never untrusted OS content.
func (s *Service) Intent(id string) (Intent, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	intent, ok := s.intents[id]
	return intent, ok
}

func (s *Service) observe(ctx context.Context, source Source) {
	for ctx.Err() == nil {
		checkCtx, cancel := context.WithTimeout(ctx, 8*time.Second)
		health, err := source.Backend.Health(checkCtx)
		cancel()
		if err == nil && source.DaemonID == "" && source.ProfileID == "" {
			source.DaemonID = health.ID
		}
		if err == nil && health.ID == source.DaemonID {
			_ = source.Client.StreamRemoteEvents(ctx, func(event client.RemoteEvent) { s.process(ctx, source, event) })
		}
		select {
		case <-ctx.Done():
			return
		case <-time.After(5 * time.Second):
		}
	}
}

func (s *Service) process(ctx context.Context, source Source, event client.RemoteEvent) {
	if ctx.Err() != nil {
		return
	}
	if event.ResourceID == "" || (event.Kind != "run" && event.Kind != "alert") {
		return
	}
	key := source.DaemonID + ":" + event.Kind + ":" + event.ResourceID
	s.mu.Lock()
	already := s.seen[key]
	s.mu.Unlock()
	if already {
		return
	}
	prefs, err := s.prefs.PopupPreferences()
	if err != nil || !prefs.Enabled || !included(prefs.DaemonIDs, source.DaemonID) {
		return
	}
	readCtx, cancel := context.WithTimeout(ctx, 4*time.Second)
	defer cancel()
	condition, severity, subject := "", "", ""
	switch event.Kind {
	case "run":
		run, readErr := source.Client.GetRun(readCtx, event.ResourceID)
		if readErr != nil || run.EndedAt == nil {
			return
		}
		if run.Outcome == domain.OutcomeSuccess {
			condition, severity = "success", "info"
		} else if run.Outcome == domain.OutcomeFailure {
			condition, severity = "failure", "error"
		} else {
			return
		}
		subject = "Task " + run.TaskID
		if task, taskErr := source.Client.GetTask(readCtx, run.TaskID); taskErr == nil && task.Task.Name != "" {
			subject = task.Task.Name
		}
	case "alert":
		alerts, readErr := source.Client.ListAlertsLimited(readCtx, false, 50)
		if readErr != nil {
			return
		}
		for _, alert := range alerts {
			if alert.ID == event.ResourceID {
				condition, severity, subject = "alert", string(alert.Severity), string(alert.Kind)
				if alert.TaskID != "" {
					subject = "Task " + alert.TaskID + ": " + string(alert.Kind)
					if task, taskErr := source.Client.GetTask(readCtx, alert.TaskID); taskErr == nil && task.Task.Name != "" {
						subject = task.Task.Name + ": " + string(alert.Kind)
					}
				} else if alert.Kind == domain.AlertService {
					subject = "Scheduler service alert"
				}
				break
			}
		}
		if condition == "" {
			return
		}
	}
	if !included(prefs.Conditions, condition) || (event.Kind == "alert" && !included(prefs.Severities, severity)) {
		return
	}
	if ctx.Err() != nil {
		return
	}
	latest, err := s.prefs.PopupPreferences()
	if err != nil || !latest.Enabled || !included(latest.DaemonIDs, source.DaemonID) || !included(latest.Conditions, condition) || (event.Kind == "alert" && !included(latest.Severities, severity)) {
		return
	}
	s.mu.Lock()
	if s.seen[key] {
		s.mu.Unlock()
		return
	}
	s.seq++
	id := fmt.Sprintf("popup-%d", s.seq)
	intent := Intent{ProfileID: source.ProfileID, DaemonID: source.DaemonID, Label: source.Label, Kind: event.Kind, RecordID: event.ResourceID}
	s.seen[key] = true
	s.order = append(s.order, key)
	s.intents[id] = intent
	if len(s.order) > maxSeen {
		delete(s.seen, s.order[0])
		s.order = s.order[1:]
	}
	if len(s.intents) > maxSeen {
		delete(s.intents, fmt.Sprintf("popup-%d", s.seq-maxSeen))
	}
	s.mu.Unlock()
	name := compact(source.Label, 48)
	if name == "" {
		name = "Scheduler"
	}
	shortID := source.DaemonID
	if len(shortID) > 8 {
		shortID = shortID[:8]
	}
	_ = s.presenter.Present(Notice{ID: id, Title: name + " [" + shortID + "]: " + condition + " (" + severity + ")", Body: compact(subject, 120), Intent: intent})
}

func included(values []string, value string) bool {
	if len(values) == 0 {
		return true
	}
	for _, candidate := range values {
		if candidate == value {
			return true
		}
	}
	return false
}

func compact(value string, limit int) string {
	value = strings.TrimSpace(strings.Map(func(char rune) rune {
		if unicode.IsControl(char) {
			return ' '
		}
		return char
	}, value))
	runes := []rune(value)
	if len(runes) > limit {
		value = string(runes[:limit-1]) + "…"
	}
	return value
}
