// Package remote provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package remote

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EnrollmentRequestCapability.
const (
	Enroll  EnrollmentRequestCapability = "enroll"
	Manage  EnrollmentRequestCapability = "manage"
	Observe EnrollmentRequestCapability = "observe"
	Operate EnrollmentRequestCapability = "operate"
)

// Valid indicates whether the value is a known member of the EnrollmentRequestCapability enum.
func (e EnrollmentRequestCapability) Valid() bool {
	switch e {
	case Enroll:
		return true
	case Manage:
		return true
	case Observe:
		return true
	case Operate:
		return true
	default:
		return false
	}
}

// Defines values for EnrollmentRequestKind.
const (
	Cli     EnrollmentRequestKind = "cli"
	Desktop EnrollmentRequestKind = "desktop"
	Json    EnrollmentRequestKind = "json"
	Mcp     EnrollmentRequestKind = "mcp"
)

// Valid indicates whether the value is a known member of the EnrollmentRequestKind enum.
func (e EnrollmentRequestKind) Valid() bool {
	switch e {
	case Cli:
		return true
	case Desktop:
		return true
	case Json:
		return true
	case Mcp:
		return true
	default:
		return false
	}
}

// EnrollmentRequest defines model for EnrollmentRequest.
type EnrollmentRequest struct {
	Capability  EnrollmentRequestCapability `json:"capability"`
	DaemonId    openapi_types.UUID          `json:"daemon_id"`
	DisplayName string                      `json:"display_name"`
	Kind        EnrollmentRequestKind       `json:"kind"`
	PairingId   openapi_types.UUID          `json:"pairing_id"`
	Phrase      string                      `json:"phrase"`
}

// EnrollmentRequestCapability defines model for EnrollmentRequest.Capability.
type EnrollmentRequestCapability string

// EnrollmentRequestKind defines model for EnrollmentRequest.Kind.
type EnrollmentRequestKind string

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// ID defines model for ID.
type ID = openapi_types.UUID

// JSONSuccess defines model for JSONSuccess.
type JSONSuccess = map[string]interface{}

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorEnvelope

// JSONBody defines model for JSONBody.
type JSONBody = map[string]interface{}

// TasksCreateJSONBody defines parameters for TasksCreate.
type TasksCreateJSONBody = map[string]interface{}

// TasksUpdateJSONBody defines parameters for TasksUpdate.
type TasksUpdateJSONBody = map[string]interface{}

// EnrollmentExchangeJSONRequestBody defines body for EnrollmentExchange for application/json ContentType.
type EnrollmentExchangeJSONRequestBody = EnrollmentRequest

// TasksCreateJSONRequestBody defines body for TasksCreate for application/json ContentType.
type TasksCreateJSONRequestBody = TasksCreateJSONBody

// TasksUpdateJSONRequestBody defines body for TasksUpdate for application/json ContentType.
type TasksUpdateJSONRequestBody = TasksUpdateJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ActorsList performs a GET /access/actors (the `ActorsList` operationId) request.
	ActorsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AlertsList performs a GET /alerts (the `AlertsList` operationId) request.
	AlertsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AlertsAcknowledge performs a POST /alerts/{id}/ack (the `AlertsAcknowledge` operationId) request.
	AlertsAcknowledge(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AuditList performs a GET /audit (the `AuditList` operationId) request.
	AuditList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CalendarRead performs a GET /calendar (the `CalendarRead` operationId) request.
	CalendarRead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnrollmentExchangeWithBody performs a POST /enroll (the `EnrollmentExchange` operationId) request,
	// with any type of body and a specified content type.
	EnrollmentExchangeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnrollmentExchange performs a POST /enroll (the `EnrollmentExchange` operationId) request.
	// Takes a body of the `application/json` content type.
	EnrollmentExchange(ctx context.Context, body EnrollmentExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EventsStream performs a GET /events (the `EventsStream` operationId) request.
	//
	// Reconnect safe read stream. Mutations are never automatically replayed.
	EventsStream(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GroupsList performs a GET /groups (the `GroupsList` operationId) request.
	GroupsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GroupsRead performs a GET /groups/{id} (the `GroupsRead` operationId) request.
	GroupsRead(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthRead performs a GET /health (the `HealthRead` operationId) request.
	HealthRead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ManifestRead performs a GET /manifest (the `ManifestRead` operationId) request.
	ManifestRead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RunsList performs a GET /runs (the `RunsList` operationId) request.
	RunsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RunsActiveList performs a GET /runs/active (the `RunsActiveList` operationId) request.
	RunsActiveList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RunsRead performs a GET /runs/{id} (the `RunsRead` operationId) request.
	RunsRead(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksList performs a GET /tasks (the `TasksList` operationId) request.
	TasksList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksCreateWithBody performs a POST /tasks (the `TasksCreate` operationId) request,
	// with any type of body and a specified content type.
	TasksCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksCreate performs a POST /tasks (the `TasksCreate` operationId) request.
	// Takes a body of the `application/json` content type.
	TasksCreate(ctx context.Context, body TasksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksDelete performs a DELETE /tasks/{id} (the `TasksDelete` operationId) request.
	TasksDelete(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksRead performs a GET /tasks/{id} (the `TasksRead` operationId) request.
	TasksRead(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksUpdateWithBody performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request,
	// with any type of body and a specified content type.
	TasksUpdateWithBody(ctx context.Context, id ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksUpdate performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request.
	// Takes a body of the `application/json` content type.
	TasksUpdate(ctx context.Context, id ID, body TasksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksDisable performs a POST /tasks/{id}/disable (the `TasksDisable` operationId) request.
	TasksDisable(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksEnable performs a POST /tasks/{id}/enable (the `TasksEnable` operationId) request.
	TasksEnable(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// TasksRunNow performs a POST /tasks/{id}/run-now (the `TasksRunNow` operationId) request.
	TasksRunNow(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ActorsList performs a GET /access/actors (the `ActorsList` operationId) request.
func (c *Client) ActorsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActorsListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AlertsList performs a GET /alerts (the `AlertsList` operationId) request.
func (c *Client) AlertsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAlertsListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AlertsAcknowledge performs a POST /alerts/{id}/ack (the `AlertsAcknowledge` operationId) request.
func (c *Client) AlertsAcknowledge(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAlertsAcknowledgeRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AuditList performs a GET /audit (the `AuditList` operationId) request.
func (c *Client) AuditList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuditListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CalendarRead performs a GET /calendar (the `CalendarRead` operationId) request.
func (c *Client) CalendarRead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCalendarReadRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// EnrollmentExchangeWithBody performs a POST /enroll (the `EnrollmentExchange` operationId) request,
// with any type of body and a specified content type.
func (c *Client) EnrollmentExchangeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnrollmentExchangeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// EnrollmentExchange performs a POST /enroll (the `EnrollmentExchange` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) EnrollmentExchange(ctx context.Context, body EnrollmentExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnrollmentExchangeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// EventsStream performs a GET /events (the `EventsStream` operationId) request.
//
// Reconnect safe read stream. Mutations are never automatically replayed.
func (c *Client) EventsStream(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEventsStreamRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GroupsList performs a GET /groups (the `GroupsList` operationId) request.
func (c *Client) GroupsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGroupsListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GroupsRead performs a GET /groups/{id} (the `GroupsRead` operationId) request.
func (c *Client) GroupsRead(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGroupsReadRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// HealthRead performs a GET /health (the `HealthRead` operationId) request.
func (c *Client) HealthRead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthReadRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ManifestRead performs a GET /manifest (the `ManifestRead` operationId) request.
func (c *Client) ManifestRead(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewManifestReadRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RunsList performs a GET /runs (the `RunsList` operationId) request.
func (c *Client) RunsList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunsListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RunsActiveList performs a GET /runs/active (the `RunsActiveList` operationId) request.
func (c *Client) RunsActiveList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunsActiveListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RunsRead performs a GET /runs/{id} (the `RunsRead` operationId) request.
func (c *Client) RunsRead(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunsReadRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksList performs a GET /tasks (the `TasksList` operationId) request.
func (c *Client) TasksList(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksListRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksCreateWithBody performs a POST /tasks (the `TasksCreate` operationId) request,
// with any type of body and a specified content type.
func (c *Client) TasksCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksCreate performs a POST /tasks (the `TasksCreate` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) TasksCreate(ctx context.Context, body TasksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksDelete performs a DELETE /tasks/{id} (the `TasksDelete` operationId) request.
func (c *Client) TasksDelete(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksDeleteRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksRead performs a GET /tasks/{id} (the `TasksRead` operationId) request.
func (c *Client) TasksRead(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksReadRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksUpdateWithBody performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request,
// with any type of body and a specified content type.
func (c *Client) TasksUpdateWithBody(ctx context.Context, id ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksUpdateRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksUpdate performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request.
// Takes a body of the `application/json` content type.
func (c *Client) TasksUpdate(ctx context.Context, id ID, body TasksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksUpdateRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksDisable performs a POST /tasks/{id}/disable (the `TasksDisable` operationId) request.
func (c *Client) TasksDisable(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksDisableRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksEnable performs a POST /tasks/{id}/enable (the `TasksEnable` operationId) request.
func (c *Client) TasksEnable(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksEnableRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// TasksRunNow performs a POST /tasks/{id}/run-now (the `TasksRunNow` operationId) request.
func (c *Client) TasksRunNow(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewTasksRunNowRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewActorsListRequest constructs an http.Request for the ActorsList method
func NewActorsListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/access/actors")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAlertsListRequest constructs an http.Request for the AlertsList method
func NewAlertsListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alerts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAlertsAcknowledgeRequest constructs an http.Request for the AlertsAcknowledge method
func NewAlertsAcknowledgeRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/alerts/%s/ack", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAuditListRequest constructs an http.Request for the AuditList method
func NewAuditListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/audit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCalendarReadRequest constructs an http.Request for the CalendarRead method
func NewCalendarReadRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/calendar")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEnrollmentExchangeRequest calls the generic EnrollmentExchange builder with application/json body
func NewEnrollmentExchangeRequest(server string, body EnrollmentExchangeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEnrollmentExchangeRequestWithBody(server, "application/json", bodyReader)
}

// NewEnrollmentExchangeRequestWithBody constructs an http.Request for the EnrollmentExchange method, with any body, and a specified content type
func NewEnrollmentExchangeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/enroll")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewEventsStreamRequest constructs an http.Request for the EventsStream method
func NewEventsStreamRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/events")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGroupsListRequest constructs an http.Request for the GroupsList method
func NewGroupsListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/groups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGroupsReadRequest constructs an http.Request for the GroupsRead method
func NewGroupsReadRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHealthReadRequest constructs an http.Request for the HealthRead method
func NewHealthReadRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewManifestReadRequest constructs an http.Request for the ManifestRead method
func NewManifestReadRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/manifest")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRunsListRequest constructs an http.Request for the RunsList method
func NewRunsListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/runs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRunsActiveListRequest constructs an http.Request for the RunsActiveList method
func NewRunsActiveListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/runs/active")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRunsReadRequest constructs an http.Request for the RunsRead method
func NewRunsReadRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/runs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTasksListRequest constructs an http.Request for the TasksList method
func NewTasksListRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTasksCreateRequest calls the generic TasksCreate builder with application/json body
func NewTasksCreateRequest(server string, body TasksCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTasksCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewTasksCreateRequestWithBody constructs an http.Request for the TasksCreate method, with any body, and a specified content type
func NewTasksCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTasksDeleteRequest constructs an http.Request for the TasksDelete method
func NewTasksDeleteRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTasksReadRequest constructs an http.Request for the TasksRead method
func NewTasksReadRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTasksUpdateRequest calls the generic TasksUpdate builder with application/json body
func NewTasksUpdateRequest(server string, id ID, body TasksUpdateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewTasksUpdateRequestWithBody(server, id, "application/json", bodyReader)
}

// NewTasksUpdateRequestWithBody constructs an http.Request for the TasksUpdate method, with any body, and a specified content type
func NewTasksUpdateRequestWithBody(server string, id ID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewTasksDisableRequest constructs an http.Request for the TasksDisable method
func NewTasksDisableRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s/disable", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTasksEnableRequest constructs an http.Request for the TasksEnable method
func NewTasksEnableRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s/enable", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewTasksRunNowRequest constructs an http.Request for the TasksRunNow method
func NewTasksRunNowRequest(server string, id ID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tasks/%s/run-now", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ActorsListWithResponse performs a GET /access/actors (the `ActorsList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ActorsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ActorsListResponse, error)

	// AlertsListWithResponse performs a GET /alerts (the `AlertsList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	AlertsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AlertsListResponse, error)

	// AlertsAcknowledgeWithResponse performs a POST /alerts/{id}/ack (the `AlertsAcknowledge` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	AlertsAcknowledgeWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*AlertsAcknowledgeResponse, error)

	// AuditListWithResponse performs a GET /audit (the `AuditList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	AuditListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AuditListResponse, error)

	// CalendarReadWithResponse performs a GET /calendar (the `CalendarRead` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	CalendarReadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CalendarReadResponse, error)

	// EnrollmentExchangeWithBodyWithResponse performs a POST /enroll (the `EnrollmentExchange` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	EnrollmentExchangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnrollmentExchangeResponse, error)

	// EnrollmentExchangeWithResponse performs a POST /enroll (the `EnrollmentExchange` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	EnrollmentExchangeWithResponse(ctx context.Context, body EnrollmentExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*EnrollmentExchangeResponse, error)

	// EventsStreamWithResponse performs a GET /events (the `EventsStream` operationId) request.
	//
	// Reconnect safe read stream. Mutations are never automatically replayed.
	//
	// Returns a wrapper object for the known response body format(s).
	EventsStreamWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*EventsStreamResponse, error)

	// GroupsListWithResponse performs a GET /groups (the `GroupsList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GroupsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GroupsListResponse, error)

	// GroupsReadWithResponse performs a GET /groups/{id} (the `GroupsRead` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GroupsReadWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*GroupsReadResponse, error)

	// HealthReadWithResponse performs a GET /health (the `HealthRead` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	HealthReadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthReadResponse, error)

	// ManifestReadWithResponse performs a GET /manifest (the `ManifestRead` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ManifestReadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ManifestReadResponse, error)

	// RunsListWithResponse performs a GET /runs (the `RunsList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	RunsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RunsListResponse, error)

	// RunsActiveListWithResponse performs a GET /runs/active (the `RunsActiveList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	RunsActiveListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RunsActiveListResponse, error)

	// RunsReadWithResponse performs a GET /runs/{id} (the `RunsRead` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	RunsReadWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*RunsReadResponse, error)

	// TasksListWithResponse performs a GET /tasks (the `TasksList` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TasksListResponse, error)

	// TasksCreateWithBodyWithResponse performs a POST /tasks (the `TasksCreate` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TasksCreateResponse, error)

	// TasksCreateWithResponse performs a POST /tasks (the `TasksCreate` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	TasksCreateWithResponse(ctx context.Context, body TasksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*TasksCreateResponse, error)

	// TasksDeleteWithResponse performs a DELETE /tasks/{id} (the `TasksDelete` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksDeleteWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksDeleteResponse, error)

	// TasksReadWithResponse performs a GET /tasks/{id} (the `TasksRead` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksReadWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksReadResponse, error)

	// TasksUpdateWithBodyWithResponse performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksUpdateWithBodyWithResponse(ctx context.Context, id ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TasksUpdateResponse, error)

	// TasksUpdateWithResponse performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	TasksUpdateWithResponse(ctx context.Context, id ID, body TasksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*TasksUpdateResponse, error)

	// TasksDisableWithResponse performs a POST /tasks/{id}/disable (the `TasksDisable` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksDisableWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksDisableResponse, error)

	// TasksEnableWithResponse performs a POST /tasks/{id}/enable (the `TasksEnable` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksEnableWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksEnableResponse, error)

	// TasksRunNowWithResponse performs a POST /tasks/{id}/run-now (the `TasksRunNow` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	TasksRunNowWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksRunNowResponse, error)
}

type ActorsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ActorsListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ActorsListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ActorsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ActorsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ActorsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AlertsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AlertsListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r AlertsListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AlertsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AlertsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AlertsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AlertsAcknowledgeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AlertsAcknowledgeResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r AlertsAcknowledgeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AlertsAcknowledgeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AlertsAcknowledgeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AlertsAcknowledgeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AuditListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AuditListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r AuditListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AuditListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuditListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AuditListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CalendarReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CalendarReadResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r CalendarReadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CalendarReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CalendarReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CalendarReadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// EnrollmentExchangeResponse401Headers the declared response headers of an HTTP 401 response for EnrollmentExchange
type EnrollmentExchangeResponse401Headers struct {
	WWWAuthenticate *string
}

type EnrollmentExchangeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *JSONSuccess
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *EnrollmentExchangeResponse401Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r EnrollmentExchangeResponse) GetJSON201() *JSONSuccess {
	return r.JSON201
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r EnrollmentExchangeResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r EnrollmentExchangeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r EnrollmentExchangeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EnrollmentExchangeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r EnrollmentExchangeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type EventsStreamResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// GetBody returns the raw response body bytes
func (r EventsStreamResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r EventsStreamResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EventsStreamResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r EventsStreamResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GroupsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GroupsListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GroupsListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GroupsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GroupsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GroupsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GroupsReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GroupsReadResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GroupsReadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GroupsReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GroupsReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GroupsReadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HealthReadResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r HealthReadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HealthReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthReadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ManifestReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ManifestReadResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ManifestReadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ManifestReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ManifestReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ManifestReadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RunsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RunsListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r RunsListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RunsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RunsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RunsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RunsActiveListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RunsActiveListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r RunsActiveListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RunsActiveListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RunsActiveListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RunsActiveListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RunsReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r RunsReadResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r RunsReadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RunsReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RunsReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RunsReadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// TasksListResponse401Headers the declared response headers of an HTTP 401 response for TasksList
type TasksListResponse401Headers struct {
	WWWAuthenticate *string
}

type TasksListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *TasksListResponse401Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TasksListResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r TasksListResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r TasksListResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// TasksCreateResponse401Headers the declared response headers of an HTTP 401 response for TasksCreate
type TasksCreateResponse401Headers struct {
	WWWAuthenticate *string
}

type TasksCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *JSONSuccess
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// Headers401 the parsed response headers for an HTTP 401 response
	Headers401 *TasksCreateResponse401Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r TasksCreateResponse) GetJSON201() *JSONSuccess {
	return r.JSON201
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r TasksCreateResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r TasksCreateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksCreateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TasksDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TasksDeleteResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r TasksDeleteResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksDeleteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TasksReadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TasksReadResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r TasksReadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksReadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksReadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksReadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TasksUpdateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TasksUpdateResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r TasksUpdateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksUpdateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksUpdateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksUpdateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TasksDisableResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TasksDisableResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r TasksDisableResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksDisableResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksDisableResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksDisableResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TasksEnableResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *JSONSuccess
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r TasksEnableResponse) GetJSON200() *JSONSuccess {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r TasksEnableResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksEnableResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksEnableResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksEnableResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type TasksRunNowResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON202 the response for an HTTP 202 `application/json` response
	JSON202 *JSONSuccess
}

// GetJSON202 returns the response for an HTTP 202 `application/json` response
func (r TasksRunNowResponse) GetJSON202() *JSONSuccess {
	return r.JSON202
}

// GetBody returns the raw response body bytes
func (r TasksRunNowResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r TasksRunNowResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r TasksRunNowResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r TasksRunNowResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ActorsListWithResponse performs a GET /access/actors (the `ActorsList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ActorsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ActorsListResponse, error) {
	rsp, err := c.ActorsList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActorsListResponse(rsp)
}

// AlertsListWithResponse performs a GET /alerts (the `AlertsList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) AlertsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AlertsListResponse, error) {
	rsp, err := c.AlertsList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAlertsListResponse(rsp)
}

// AlertsAcknowledgeWithResponse performs a POST /alerts/{id}/ack (the `AlertsAcknowledge` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) AlertsAcknowledgeWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*AlertsAcknowledgeResponse, error) {
	rsp, err := c.AlertsAcknowledge(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAlertsAcknowledgeResponse(rsp)
}

// AuditListWithResponse performs a GET /audit (the `AuditList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) AuditListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AuditListResponse, error) {
	rsp, err := c.AuditList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuditListResponse(rsp)
}

// CalendarReadWithResponse performs a GET /calendar (the `CalendarRead` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CalendarReadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CalendarReadResponse, error) {
	rsp, err := c.CalendarRead(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCalendarReadResponse(rsp)
}

// EnrollmentExchangeWithBodyWithResponse performs a POST /enroll (the `EnrollmentExchange` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) EnrollmentExchangeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnrollmentExchangeResponse, error) {
	rsp, err := c.EnrollmentExchangeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnrollmentExchangeResponse(rsp)
}

// EnrollmentExchangeWithResponse performs a POST /enroll (the `EnrollmentExchange` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) EnrollmentExchangeWithResponse(ctx context.Context, body EnrollmentExchangeJSONRequestBody, reqEditors ...RequestEditorFn) (*EnrollmentExchangeResponse, error) {
	rsp, err := c.EnrollmentExchange(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnrollmentExchangeResponse(rsp)
}

// EventsStreamWithResponse performs a GET /events (the `EventsStream` operationId) request.
//
// Reconnect safe read stream. Mutations are never automatically replayed.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) EventsStreamWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*EventsStreamResponse, error) {
	rsp, err := c.EventsStream(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEventsStreamResponse(rsp)
}

// GroupsListWithResponse performs a GET /groups (the `GroupsList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GroupsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GroupsListResponse, error) {
	rsp, err := c.GroupsList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGroupsListResponse(rsp)
}

// GroupsReadWithResponse performs a GET /groups/{id} (the `GroupsRead` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GroupsReadWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*GroupsReadResponse, error) {
	rsp, err := c.GroupsRead(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGroupsReadResponse(rsp)
}

// HealthReadWithResponse performs a GET /health (the `HealthRead` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) HealthReadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthReadResponse, error) {
	rsp, err := c.HealthRead(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthReadResponse(rsp)
}

// ManifestReadWithResponse performs a GET /manifest (the `ManifestRead` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ManifestReadWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ManifestReadResponse, error) {
	rsp, err := c.ManifestRead(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseManifestReadResponse(rsp)
}

// RunsListWithResponse performs a GET /runs (the `RunsList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) RunsListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RunsListResponse, error) {
	rsp, err := c.RunsList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunsListResponse(rsp)
}

// RunsActiveListWithResponse performs a GET /runs/active (the `RunsActiveList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) RunsActiveListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*RunsActiveListResponse, error) {
	rsp, err := c.RunsActiveList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunsActiveListResponse(rsp)
}

// RunsReadWithResponse performs a GET /runs/{id} (the `RunsRead` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) RunsReadWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*RunsReadResponse, error) {
	rsp, err := c.RunsRead(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunsReadResponse(rsp)
}

// TasksListWithResponse performs a GET /tasks (the `TasksList` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksListWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*TasksListResponse, error) {
	rsp, err := c.TasksList(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksListResponse(rsp)
}

// TasksCreateWithBodyWithResponse performs a POST /tasks (the `TasksCreate` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TasksCreateResponse, error) {
	rsp, err := c.TasksCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksCreateResponse(rsp)
}

// TasksCreateWithResponse performs a POST /tasks (the `TasksCreate` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksCreateWithResponse(ctx context.Context, body TasksCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*TasksCreateResponse, error) {
	rsp, err := c.TasksCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksCreateResponse(rsp)
}

// TasksDeleteWithResponse performs a DELETE /tasks/{id} (the `TasksDelete` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksDeleteWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksDeleteResponse, error) {
	rsp, err := c.TasksDelete(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksDeleteResponse(rsp)
}

// TasksReadWithResponse performs a GET /tasks/{id} (the `TasksRead` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksReadWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksReadResponse, error) {
	rsp, err := c.TasksRead(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksReadResponse(rsp)
}

// TasksUpdateWithBodyWithResponse performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksUpdateWithBodyWithResponse(ctx context.Context, id ID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*TasksUpdateResponse, error) {
	rsp, err := c.TasksUpdateWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksUpdateResponse(rsp)
}

// TasksUpdateWithResponse performs a PATCH /tasks/{id} (the `TasksUpdate` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksUpdateWithResponse(ctx context.Context, id ID, body TasksUpdateJSONRequestBody, reqEditors ...RequestEditorFn) (*TasksUpdateResponse, error) {
	rsp, err := c.TasksUpdate(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksUpdateResponse(rsp)
}

// TasksDisableWithResponse performs a POST /tasks/{id}/disable (the `TasksDisable` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksDisableWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksDisableResponse, error) {
	rsp, err := c.TasksDisable(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksDisableResponse(rsp)
}

// TasksEnableWithResponse performs a POST /tasks/{id}/enable (the `TasksEnable` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksEnableWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksEnableResponse, error) {
	rsp, err := c.TasksEnable(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksEnableResponse(rsp)
}

// TasksRunNowWithResponse performs a POST /tasks/{id}/run-now (the `TasksRunNow` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) TasksRunNowWithResponse(ctx context.Context, id ID, reqEditors ...RequestEditorFn) (*TasksRunNowResponse, error) {
	rsp, err := c.TasksRunNow(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseTasksRunNowResponse(rsp)
}

// ParseActorsListResponse parses an HTTP response from a ActorsListWithResponse call
func ParseActorsListResponse(rsp *http.Response) (*ActorsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ActorsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAlertsListResponse parses an HTTP response from a AlertsListWithResponse call
func ParseAlertsListResponse(rsp *http.Response) (*AlertsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AlertsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAlertsAcknowledgeResponse parses an HTTP response from a AlertsAcknowledgeWithResponse call
func ParseAlertsAcknowledgeResponse(rsp *http.Response) (*AlertsAcknowledgeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AlertsAcknowledgeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAuditListResponse parses an HTTP response from a AuditListWithResponse call
func ParseAuditListResponse(rsp *http.Response) (*AuditListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuditListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCalendarReadResponse parses an HTTP response from a CalendarReadWithResponse call
func ParseCalendarReadResponse(rsp *http.Response) (*CalendarReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CalendarReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseEnrollmentExchangeResponse parses an HTTP response from a EnrollmentExchangeWithResponse call
func ParseEnrollmentExchangeResponse(rsp *http.Response) (*EnrollmentExchangeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EnrollmentExchangeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers EnrollmentExchangeResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseEventsStreamResponse parses an HTTP response from a EventsStreamWithResponse call
func ParseEventsStreamResponse(rsp *http.Response) (*EventsStreamResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EventsStreamResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGroupsListResponse parses an HTTP response from a GroupsListWithResponse call
func ParseGroupsListResponse(rsp *http.Response) (*GroupsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GroupsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGroupsReadResponse parses an HTTP response from a GroupsReadWithResponse call
func ParseGroupsReadResponse(rsp *http.Response) (*GroupsReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GroupsReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHealthReadResponse parses an HTTP response from a HealthReadWithResponse call
func ParseHealthReadResponse(rsp *http.Response) (*HealthReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseManifestReadResponse parses an HTTP response from a ManifestReadWithResponse call
func ParseManifestReadResponse(rsp *http.Response) (*ManifestReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ManifestReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRunsListResponse parses an HTTP response from a RunsListWithResponse call
func ParseRunsListResponse(rsp *http.Response) (*RunsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RunsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRunsActiveListResponse parses an HTTP response from a RunsActiveListWithResponse call
func ParseRunsActiveListResponse(rsp *http.Response) (*RunsActiveListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RunsActiveListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRunsReadResponse parses an HTTP response from a RunsReadWithResponse call
func ParseRunsReadResponse(rsp *http.Response) (*RunsReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RunsReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTasksListResponse parses an HTTP response from a TasksListWithResponse call
func ParseTasksListResponse(rsp *http.Response) (*TasksListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers TasksListResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseTasksCreateResponse parses an HTTP response from a TasksCreateWithResponse call
func ParseTasksCreateResponse(rsp *http.Response) (*TasksCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	switch {
	case rsp.StatusCode == 401:
		var headers TasksCreateResponse401Headers
		if values := rsp.Header.Values("WWW-Authenticate"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "WWW-Authenticate", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.WWWAuthenticate = &value
		}
		response.Headers401 = &headers
	}

	return response, nil
}

// ParseTasksDeleteResponse parses an HTTP response from a TasksDeleteWithResponse call
func ParseTasksDeleteResponse(rsp *http.Response) (*TasksDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTasksReadResponse parses an HTTP response from a TasksReadWithResponse call
func ParseTasksReadResponse(rsp *http.Response) (*TasksReadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksReadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTasksUpdateResponse parses an HTTP response from a TasksUpdateWithResponse call
func ParseTasksUpdateResponse(rsp *http.Response) (*TasksUpdateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksUpdateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTasksDisableResponse parses an HTTP response from a TasksDisableWithResponse call
func ParseTasksDisableResponse(rsp *http.Response) (*TasksDisableResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksDisableResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTasksEnableResponse parses an HTTP response from a TasksEnableWithResponse call
func ParseTasksEnableResponse(rsp *http.Response) (*TasksEnableResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksEnableResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseTasksRunNowResponse parses an HTTP response from a TasksRunNowWithResponse call
func ParseTasksRunNowResponse(rsp *http.Response) (*TasksRunNowResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &TasksRunNowResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest JSONSuccess
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}
