import { useState } from 'react'
import { Button, CardSection, DescriptionList, Disclosure, Field, FormGrid, Notice, StatePanel, StatusLabel } from '../components'
import type { AgentAccessBridge } from './model'
import { useAgentAccess } from './store'

export function AgentAccessPage({ bridge, available, refreshToken }: { bridge: AgentAccessBridge; available: boolean; refreshToken: number }) {
  const access = useAgentAccess(bridge, available, refreshToken)
  const [name, setName] = useState('Codex')
  const [port, setPort] = useState('43123')
  const [origins, setOrigins] = useState('')
  if (!available) return <StatePanel title="Agent Access unavailable" detail="Reconnect to the local scheduler service to inspect or control agent access." />
  if (!access.workspace && access.message) return <StatePanel title="Agent Access unavailable" detail={access.message} action="Try again" onAction={() => void access.load()} />
  if (!access.workspace) return <StatePanel title="Loading Agent Access" detail="Reading the local MCP access boundary." busy />
  const http = access.workspace.http
  const enableForm = <form onSubmit={(event) => { event.preventDefault(); void access.enable({ clientName: name, port: Number(port), allowedOrigins: origins.split(/\r?\n/).map((value) => value.trim()).filter(Boolean) }) }}><FormGrid><Field label="Client name"><input value={name} maxLength={64} required onChange={(event) => setName(event.target.value)} /></Field><Field label="Loopback port"><input value={port} type="number" min="1" max="65535" required onChange={(event) => setPort(event.target.value)} /></Field><Field label="Allowed browser origins (one per line)"><textarea value={origins} placeholder="http://127.0.0.1:3000" onChange={(event) => setOrigins(event.target.value)} /></Field></FormGrid><Button pending={access.pending} type="submit">Enable and copy credential</Button></form>
  return <section aria-labelledby="agent-access-title"><header className="page-header"><div><p className="eyebrow">This computer</p><h1 id="agent-access-title">Agent Access</h1><p>Understand exactly what local agents can read and close optional network access.</p></div><Button variant="secondary" onClick={() => void access.openGuide()}>Setup guide</Button></header>{access.message && <Notice title="Agent Access status" tone={access.message.includes('could not') || access.message.includes('unavailable') ? 'warning' : 'info'}>{access.message}</Notice>}<div className="admin-stack"><div className="settings-grid"><CardSection eyebrow="Process access" title="stdio" status={<StatusLabel tone="positive">Available on demand</StatusLabel>}><p>{access.workspace.stdioDescription}</p></CardSection><CardSection eyebrow="Authority" title="What agents can do"><div className="authority-list">{access.workspace.authorities.map((authority) => <section key={authority.name}><h3>{authority.name} <span className="muted">({authority.status === 'available' ? 'Available' : 'Future, unavailable'})</span></h3><p>{authority.description}</p></section>)}</div></CardSection></div><CardSection eyebrow="Optional network access" title="Localhost HTTP" status={<StatusLabel tone={http.enabled ? 'positive' : 'neutral'}>{http.enabled ? 'Active' : 'Off'}</StatusLabel>}>{http.enabled ? <><DescriptionList><dt>Client</dt><dd>{http.clientName}</dd><dt>Endpoint</dt><dd><code className="operational-value">{http.endpoint}</code></dd><dt>Allowed browser origins</dt><dd className="operational-value">{http.allowedOrigins.length ? http.allowedOrigins.join(', ') : 'None'}</dd><dt>Credential fingerprint</dt><dd><code className="operational-value">{http.credentialFingerprint}</code></dd><dt>Enabled</dt><dd>{http.enabledAt}</dd><dt>Last successful access</dt><dd>{http.lastAccessedAt ?? 'No successful requests yet'}</dd><dt>Successful requests</dt><dd>{http.requestCount}</dd></DescriptionList><div className="actions"><Button disabled={access.pending} onClick={() => void access.rotate()}>Rotate credential</Button><Button variant="secondary" disabled={access.pending} onClick={() => void access.revoke()}>Revoke access</Button></div></> : <Disclosure summary="Configure localhost HTTP">{enableForm}</Disclosure>}</CardSection></div></section>
}
